apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zli535ah4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zli535ah4-java-springboot-gitops